### ISSUE TITLE
not working on another wooCommerce

### ISSUE THREAD

**Issue by pishguy** [gilokimu/woocommerce-android-sdk#5]
after testing your application with your web site consumer key and password that work fine, now i change them on my own site and when i test application to get products list i get this message:
```
Response{protocol=http/1.1, code=401,
message=Unauthorized, url=http://www.aklin.ir/wp//wp-json/wc/v2/products?oauth_consumer_key=ck_c559b86adc5460395e3ae483b852201615d29712&oauth_nonce=9.55824708358162E7&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1555420204&oauth_signature=4R%2BipUXvIJBvO2OQjnvnMPLX6WU%3D
```

i installed and enabled wp-json plugin on this website

```
class Main : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        val woocommerce = Woocommerce.Builder()
                .setSiteUrl("http://www.aklin.ir/wp")
                .setApiVersion(Woocommerce.API_V2)
                .setConsumerKey("ck_c559b86adc5460395e3ae483b852201615d29712")
                .setConsumerSecret("cs_5aaa22e54cd35fd42e490ab12c22afb4d99b6225")
                .build()

        woocommerce.products.enqueue(object : Callback<List<Product>> {
            override fun onResponse(call: Call<List<Product>>, response: Response<List<Product>>) {
                val productsResponse = response.body()
            }

            override fun onFailure(call: Call<List<Product>>, t: Throwable) {

            }
        })
    }
}
```

is any special settings on woocommerce?

**Comment by gilokimu** [comment]
This url does not look right

```
Response{protocol=http/1.1, code=401,
message=Unauthorized, url=http://www.aklin.ir/wp//wp-json/wc/v2/products?oauth_consumer_key=ck_c559b86adc5460395e3ae483b852201615d29712&oauth_nonce=9.55824708358162E7&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1555420204&oauth_signature=4R%2BipUXvIJBvO2OQjnvnMPLX6WU%3D
```

http://www.aklin.ir/wp//wp-json/ either you defined the url with a trailing slash or there is also an error on my end. I will looking into, my morning - in about 6 hours

**Comment by MahdiPishguy** [comment]
i check that. i have problem tooThanksSent from my Huawei Mobile-------- Original Message --------Subject: Re: [gilokimu/WooDroid] not working on another wooCommerce (#5)From: Gilbert Kimutai To: gilokimu/WooDroid CC: Mahdi Pishguy ,Author This url does not look right
Response{protocol=http/1.1, code=401,
message=Unauthorized, url=http://www.aklin.ir/wp//wp-json/wc/v2/products?oauth_consumer_key=ck_c559b86adc5460395e3ae483b852201615d29712&oauth_nonce=9.55824708358162E7&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1555420204&oauth_signature=4R%2BipUXvIJBvO2OQjnvnMPLX6WU%3D

http://www.aklin.ir/wp//wp-json/ either you defined the url with a trailing slash or there is also an error on my end. I will looking into, my morning - in about 6 hours

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/gilokimu/WooDroid","title":"gilokimu/WooDroid","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/gilokimu/WooDroid"}},"updates":{"snippets":[{"icon":"PERSON","message":"@gilokimu in #5: This url does not look right\r\n\r\n```\r\nResponse{protocol=http/1.1, code=401,\r\nmessage=Unauthorized, url=http://www.aklin.ir/wp//wp-json/wc/v2/products?oauth_consumer_key=ck_c559b86adc5460395e3ae483b852201615d29712\u0026oauth_nonce=9.55824708358162E7\u0026oauth_signature_method=HMAC-SHA1\u0026oauth_timestamp=1555420204\u0026oauth_signature=4R%2BipUXvIJBvO2OQjnvnMPLX6WU%3D\r\n```\r\n\r\nhttp://www.aklin.ir/wp//wp-json/ either you defined the url with a trailing slash or there is also an error on my end. I will looking into, my morning - in about 6 hours\r\n"}],"action":{"name":"View Issue","url":"https://github.com/gilokimu/WooDroid/issues/5#issuecomment-483782768"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/gilokimu/WooDroid/issues/5#issuecomment-483782768",
"url": "https://github.com/gilokimu/WooDroid/issues/5#issuecomment-483782768",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by pishguy** [comment]
@gilokimu it seems problem resolved, please let me to test more, thanks
